### PR TITLE
Upgrade to TeaVM 0.5.1

### PR DESCRIPTION
**Pull request by winniehell**

### CODE REVIEW

**Comment by andrewforester** [comment]
@winniehell Thanks! With previous version of TeaVM it can't transpile some of my code like this
```java
public static void main(String[] args) {
    HTMLDocument.current().getElementById("id").setInnerHTML("Ahaha!");
}
```
It works now though I need to clone your fork and publish it to my local maven repository.

@edibleday Thank you for this great tool. It's more comfortable to use it from gradle. I kindly ask you to merge this PR and publish plugin to jitpack or whatever you're using.

**Comment by renatoathaydes** [comment]
ping @n3o59hf. Any reason to not merge this PR?

**Comment by vic-cw** [comment]
@andriipanasiuk I suggest to move to [@renatoathaydes' fork](https://github.com/renatoathaydes/teavm-gradle-plugin)

**Comment by renatoathaydes** [comment]
Just for everyone's information: @vic-cw will take over the fork instead of me :) I will try to help as much as I can. Let's hope this plugin gets the treatment it deserves from now on, and hope others also join the effort to maintain it!

**Comment by vic-cw** [comment]
For easy reference here's my fork: https://github.com/vic-cw/teavm-gradle-plugin

**Pull request closed without merging**
